<option value="" disabled selected>{{__('Select font type')}}</option>
<option value="cairo" >cairo ( {{__('Arabic')}} )</option>
<option value="amiri">amiri ( {{__('Arabic')}} )</option>
<option value="amiri-bold">amiri-bold ( {{__('Arabic')}} )</option>
<option value="amiri-bold-italic">amiri-bold-italic ( {{__('Arabic')}} )</option>
<option value="amiri-italic">amiri-italic ( {{__('Arabic')}} )</option>
<option value="janna">janna ( {{__('Arabic')}} )</option>
<option value="markazi">markazi ( {{__('Arabic')}} )</option>
<option value="elmessiri">elmessiri ( {{__('Arabic')}} )</option>
<option value="sans-serif">sans-serif ( {{__('Arabic')}} )</option>
<option value="DejaVu Sans">DejaVu Sans ( {{__('Arabic')}} )</option>
<option value="lateef">lateef ( {{__('Arabic')}} )</option>
<option value="serif">serif </option>
<option value="cairo-black" >cairo-black</option>
<option value="cairo-bold" >cairo-bold</option>
<option value="cairo-extra-light">cairo-extra-light</option>
<option value="cairo-light">cairo-light</option>
<option value="cairo-semi-bold">cairo-semi-bold</option>
<option value="tajawal">tajawal</option>
<option value="mada">mada</option>
<option value="lemonada">lemonada</option>
<option value="kufam">kufam</option>
<option value="jomhuria">jomhuria</option>
<option value="changa">changa</option>
<option value="courier">courier</option>
<option value="ranchers">ranchers</option>
<option value="open-sans">open-sans</option>
<option value="open-sans-bold">open-sans-bold</option>
<option value="open-sans-bold-italic">open-sans-bold-italic</option>
<option value="open-sans-extra-bold">open-sans-extra-bold</option>
<option value="open-sans-semi-bold">open-sans-semi-bold</option>
<option value="open-sans-light">open-sans-light</option>
<option value="redressed">redressed</option>
<option value="lato-black">lato-black</option>
<option value="lato-bold">lato-bold</option>
<option value="lato">lato</option>
<option value="lato-thin">lato-thin</option>