export const Colors = {
  colorWhite: '#fff',
  colorBlack: '#000',
  colorGrey: 'grey',
  colorRed: '#FF0000',
  colorGullGray: '#96A2B5',
  colorAzureRadiance: '#007AFF',
  colorAmber: '#FEC107',
  colorEucalyptus: '#27A844',
  Tradewind: '#eceff1',
  colorOceanGreen: '#4CAC8C',
  colorDarkTan: '#6B0F1A',
  colorRedViolet: '#B91372',
  colorWhisper: '#F6F5FA',
  colorMidnightBlue: '#011F6A',
};
